"""empty message

Revision ID: 2eb771af0451
Revises: 67bbbd5dc5eb
Create Date: 2022-02-06 21:35:14.932910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb771af0451'
down_revision = '67bbbd5dc5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
