"""empty message

Revision ID: 67bbbd5dc5eb
Revises: 962c77749d9e
Create Date: 2022-02-06 19:42:38.901740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bbbd5dc5eb'
down_revision = '962c77749d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
