"""empty message

Revision ID: aadcd76b537c
Revises: 44e8d1b7436e
Create Date: 2022-02-07 09:19:04.051072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadcd76b537c'
down_revision = '44e8d1b7436e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
